### ISSUE TITLE
php stack image not found

### ISSUE THREAD

**Issue by dgncan** [dmstr/docker-yii2-app#1]
Hi,
I want to try this app. 
But when I run it: `~ docker-compose up -d`
Return: 
Creating network "yii2app_default" with the default driver
ERROR: 404 page not found
I check your php stack image path "[http://registry-v2.hrzg.de/dmstr/yii2-app](http://registry-v2.hrzg.de/dmstr/yii2-app)"
same return

P.S. I'm sorry for my bad english

Dogan

**Comment by schmunk42** [comment]
Sorry, just pushed my latest commit :)

Should be fixed, see https://github.com/dmstr/docker-yii2-app/blob/master/.env-dist#L8

**Comment by dgncan** [comment]
I guess that was the wrong path: `dmstr/yii2-app`
Actually: `dmstr/php-yii2`

**Comment by schmunk42** [comment]
@dgncan I've updated the comments in `.env-dist`. 

While in `Dockerfile` we build `FROM dmstr/php-yii2`, the image which is built is named `dmstr/yii2-app` - you should change that to your registry/project, eg. `registry.dgncan.com/myproject/yii2`.

**Comment by dgncan** [comment]
@schmunk42 :) Thank you for reply. I'm new on Docker. I am learning.
