### ISSUE TITLE
nginx will serve the wrong page unless you disable the default configurartion

### ISSUE THREAD

**Issue by xor76** [dmstr/docker-yii2-app#2]
After following the instruction in the README I have tried to connect to the nginx server and I have got the default nginx landing page.
A quick way to fix this is the following
1) get a shell within the nginx container 
  #docker-compose exec web bash
2) rename the default conf file for nginx
  # mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.disabled
3) Force nginx process to read the config change
  #kill -HUP $(cat /var/run/nginx.pid)

If all worked as expected Yii application should be available as root page at
http://localhost:32768

**Comment by schmunk42** [comment]
I could not reproduce this with `docker-yii2-app`, although I've seen similar errors with other projects.

Could you try upgrading the nginx image to `1.9-5.1.1` and see if this fixes your issue?

What's your host OS and docker, docker-compose version?

**Comment by xor76** [comment]
Upgrading the nginx image to 1.9-5.1.1 fix the issue for me.

My current env

OS X Sierra
$docker -v
Docker version 1.12.3, build 6b644ec, experimental
$ docker-compose -v
docker-compose version 1.8.1, build 878cff1
