### ISSUE TITLE
Windows failes finding docker-compose file

### ISSUE THREAD

**Issue by RdeWilde** [dmstr/docker-yii2-app#3]
```
docker-compose up -d
←[31mERROR←[0m: .IOError: [Errno 22] invalid mode ('r') or filename: u'.\\"docker-compose.yml:docker-compose.dev.yml"'
```

Probably because the slashes or colon `:`. Changes it to without slashes but same error:

```
COMPOSE_FILE=docker-compose.yml:docker-compose.dev.yml
```

Tried `.\\` and `./` and without and `\\`

Maybe it is

**Comment by schmunk42** [comment]
Could you try setting [`COMPOSE_CONVERT_WINDOWS_PATHS`](https://docs.docker.com/compose/reference/envvars/#/composeconvertwindowspaths).

Or use `;`, see also https://github.com/docker/compose/issues/3462

**Comment by frankthoeny** [comment]
Did that work for you? I am having this same issue.

**Comment by schmunk42** [comment]
@J-Reichl Can you verify this?

**Comment by J-Reichl** [comment]
I've experienced the exact same issue on a Windows 10 machine and setting `COMPOSE_CONVERT_WINDOWS_PATHS` to TRUE didn't help. 
But using `;` to separate the two `COMPOSE_FILE`paths solved the issue for me.
![bildschirmfoto 2017-11-27 um 11 51 44](https://user-images.githubusercontent.com/18026410/33263304-9a38468e-d369-11e7-9051-a16ef02e4ba5.png)

**Comment by schmunk42** [comment]
@J-Reichl Could you also try this on Windows...

    COMPOSE_PATH_SEPARATOR=":" docker-compose config

---

[edit]
From reading the docs, I think `COMPOSE_CONVERT_WINDOWS_PATHS` only applies to volumes, but not `COMPOSE_FILE`.
