### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory / Connection refused

### ISSUE THREAD

**Issue by zmiftah** [dmstr/docker-yii2-app#4]
So i just want to connect the container to my local mysql server, but failed.

This is the error:

> Database Exception – yii\db\Exception
> SQLSTATE[HY000] [2002] No such file or directory
> ↵
> Caused by: PDOException
> SQLSTATE[HY000] [2002] No such file or directory
> 
> in /app/vendor/yiisoft/yii2/db/Connection.php at line 602

And this is my db config:

```
'db' => [
	'class' => 'yii\db\Connection',
	'dsn' => 'mysql:host=localhost;dbname=project_core', //172.24.0.3
	'username' => 'root',
	'password' => 'password',
	'charset' => 'utf8',
],
```

After i change my config from `localhost` to `192.168.120.1`, i got this error:

> Database Exception – yii\db\Exception
> SQLSTATE[HY000] [2002] Connection refused
> ↵
> Caused by: PDOException
> SQLSTATE[HY000] [2002] Connection refused
> 
> in /app/vendor/yiisoft/yii2/db/Connection.php at line 602

Could somebody tell me what is happening? Thanks

**Comment by schmunk42** [comment]
Which kind of host OS (Mac, Win, Linux) and Docker are you using (boot2docker, docker-toolbox, Docker for Mac, docker-machine)?

**Comment by zmiftah** [comment]
Thanks, @schmunk42

I use Linuxmint 18.1 and docker-machine / docker-compose

**Comment by schmunk42** [comment]
For debugging you can go into the php container with `docker-compose run --rm php bash` and run `mysql` commands from there.

Can you ping `192.168.120.1`, does your mysql user have permissions from any host (`%`) since you're coming from the container?

**Comment by zmiftah** [comment]
Yes, i can ping to `192.168.120.1`, and also add % to my mysql priviledge.

I also tried to connect with this `mysql -uroot -h192.168.120.1 --port=3306 -p` and got this message: `ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.120.1' (111)`

**Comment by schmunk42** [comment]
So, you've linuxmint as your host running mysql and a docker-machine VM in which runs Docker and the container.

If so, you need to forward the MySQL port to the VM **or** use the IP of your host, eg. one assigned via DHCP from your local network. 

The exact configuration might vary depending on your setup.

**Comment by zmiftah** [comment]
Ok, i will try your solution, thanks

**Comment by schmunk42** [comment]
Closing this. Actually it's more a Docker issue, but feel free to comment here.

**Comment by jesusvallez** [comment]
I have the same problem =S 

EDIT: this is the solution

In your config file **docker-composer.yml**
```
  mysql:
    image: 'mysql:latest'
    volumes:
        - ./docker/dbdata:/var/lib/mysql
    ports:
        - '3306:3306'
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: pass
       MYSQL_DATABASE: database
```

In your project **db.php**
```
return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=mysql;dbname=database',
    'username' => 'root',
    'password' => 'pass',
    'charset' => 'utf8',
];
```

**Comment by anandSug** [comment]
@jesusvallez how will you convert this as buildspec.yml file that we can use in aws server
